### ISSUE TITLE
Pas de taff au Quebec, mana money ?

### ISSUE THREAD

**Issue by AbcSxyZ** [EPgg92/bootcamp-python42-day02#1]
Day 02, ex05, faire une classe qui fait une moyenne et quelques fonctions de math 🤯, et d'ici la fin de la semaine, utilisation de ces fonctions avec pandas 🏆 ! 

Du coup je me demandais si tu comptais vraiment prendre du bootcamp quelques notions, ou si c'est le pôle précarité qui te poussais à te surpasser pour quelques "manas" car manque de taff au quebec ?

Parce que je vois passez tes repo, et ça me surprend de te voir apprendre les bases de python, ça doit vraiment être la galère !

**Comment by EPgg92** [comment]
Hello! 
Et oui c'est une initiation ! Ça ne sera pas une révolution au niveau du contenu. 

Alors qu'elles sont les raisons pour laquelle je fais ce bootcamp:
- je compte approfondir ce que je  ne connaissais pas ou mal ou que de surface. Tu vois ca permet : de comparer ce je sais et ce que je devrais savoir, de remettre en question mes connaissances, de passer mes au crible du _is the best way_  mes pratiques.
- Je teste ma productivité, à prototyper et a cracher de la ligne, ce qui a toujours pêcher chez moi (bonne exemple d01 non fini car j'ai passer trop de temps à me doc, [se doc c'est bien mais quand t'as des deadlines il faut savoir faire la
 part des choses])
- je te remercie de t'inquièter mais mes économies sont ok (j'osef du mana). Pour le moment je suis littéralement en mode touriste au Québec. En effet je ne peux pas décrocher mon permis de travail tant que je n'ai pas fait un tour du poteau aux US. Du coup pas avant le 21 juin apparemment (je croise les doigts) vu que la frontière entre les US Et le Canada sont fermés jusque là. Et je t'avoue que ma recherche d'emploi et la demande ont fortement diminué depuis l'arrivée de la COVID. 
- J'ai du temps (cf _previous_ )
- Ça doit te paraître étrange mais je suis ce genre de personne qui apprend mieux dans un mouvement collectif que reclu dans mon coin. 
- bref ...

Et toi comment vas tu aussi?
Qu'est-ce que tu fais à part _stalk_ les gens sur GitHub? 
(Si tu réponds, passe par un canal privé. GitHub c'est pas facebook!  à moins que t'es une pull-request LOL)

En espérant t'avoir répondu,
Je te remercie pour le sarcasme.
